In [1]:
from statsbombpy import sb
competitions = sb.competitions()
competitions.head()

C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

,competition_id,season_id,country_name,competition_name,competition_gender,competition_youth,competition_international,season_name,match_updated,match_updated_360,match_available_360,match_available
0,9,281,Germany,1. Bundesliga,male,False,False,2023/2024,2024-09-28T20:46:38.893391,2025-11-15T23:17:41.827093,2025-11-15T23:17:41.827093,2024-09-28T20:46:38.893391
1,9,27,Germany,1. Bundesliga,male,False,False,2015/2016,2024-05-19T11:11:14.192381,NaN,NaN,2024-05-19T11:11:14.192381
2,1267,107,Africa,African Cup of Nations,male,False,True,2023,2026-05-12T21:18:08.827431,2026-05-02T02:07:18.902396,2026-05-02T02:07:18.902396,2026-05-12T21:18:08.827431
3,16,4,Europe,Champions League,male,False,False,2018/2019,2026-05-15T15:54:04.598614,2021-06-13T16:17:31.694,NaN,2026-05-15T15:54:04.598614
4,16,1,Europe,Champions League,male,False,False,2017/2018,2024-02-13T02:35:28.134882,2021-06-13T16:17:31.694,NaN,2024-02-13T02:35:28.134882

In [2]:
# Show all competitions/seasons, just the columns we care about
competitions[['competition_id', 'season_id', 'country_name',
              'competition_name', 'season_name']]

,competition_id,season_id,country_name,competition_name,season_name
0,9,281,Germany,1. Bundesliga,2023/2024
1,9,27,Germany,1. Bundesliga,2015/2016
2,1267,107,Africa,African Cup of Nations,2023
3,16,4,Europe,Champions League,2018/2019
4,16,1,Europe,Champions League,2017/2018
...,...,...,...,...,...
75,35,75,Europe,UEFA Europa League,1988/1989
76,53,315,Europe,UEFA Women's Euro,2025
77,53,106,Europe,UEFA Women's Euro,2022
78,72,107,International,Women's World Cup,2023
79,72,30,International,Women's World Cup,2019

In [3]:
import pandas as pd
pd.set_option('display.max_rows', None)

competitions[['competition_id', 'season_id', 'country_name',
              'competition_name', 'season_name']]

,competition_id,season_id,country_name,competition_name,season_name
0,9,281,Germany,1. Bundesliga,2023/2024
1,9,27,Germany,1. Bundesliga,2015/2016
2,1267,107,Africa,African Cup of Nations,2023
3,16,4,Europe,Champions League,2018/2019
4,16,1,Europe,Champions League,2017/2018
5,16,2,Europe,Champions League,2016/2017
6,16,27,Europe,Champions League,2015/2016
7,16,26,Europe,Champions League,2014/2015
8,16,25,Europe,Champions League,2013/2014
9,16,24,Europe,Champions League,2012/2013
10,16,23,Europe,Champions League,2011/2012
11,16,22,Europe,Champions League,2010/2011
12,16,21,Europe,Champions League,2009/2010
13,16,41,Europe,Champions League,2008/2009
14,16,39,Europe,Champions League,2006/2007
15,16,37,Europe,Champions League,2004/2005
16,16,44,Europe,Champions League,2003/2004
17,16,76,Europe,Champions League,1999/2000
18,16,277,Europe,Champions League,1972/1973
19,16,71,Europe,Champions League,1971/1972
20,16,276,Europe,Champions League,1970/1971
21,223,282,South America,Copa America,2024
22,87,84,Spain,Copa del Rey,1983/1984
23,87,268,Spain,Copa del Rey,1982/1983
24,87,279,Spain,Copa del Rey,1977/1978
25,37,281,England,FA Women's Super League,2023/2024
26,37,90,England,FA Women's Super League,2020/2021
27,37,42,England,FA Women's Super League,2019/2020
28,37,4,England,FA Women's Super League,2018/2019
29,1470,274,International,FIFA U20 World Cup,1979
30,43,106,International,FIFA World Cup,2022
31,43,3,International,FIFA World Cup,2018
32,43,55,International,FIFA World Cup,1990
33,43,54,International,FIFA World Cup,1986
34,43,51,International,FIFA World Cup,1974
35,43,272,International,FIFA World Cup,1970
36,43,270,International,FIFA World Cup,1962
37,43,269,International,FIFA World Cup,1958
38,135,281,Germany,Frauen Bundesliga,2023/2024
39,1238,108,India,Indian Super league,2021/2022
40,11,90,Spain,La Liga,2020/2021
41,11,42,Spain,La Liga,2019/2020
42,11,4,Spain,La Liga,2018/2019
43,11,1,Spain,La Liga,2017/2018
44,11,2,Spain,La Liga,2016/2017
45,11,27,Spain,La Liga,2015/2016
46,11,26,Spain,La Liga,2014/2015
47,11,25,Spain,La Liga,2013/2014
48,11,24,Spain,La Liga,2012/2013
49,11,23,Spain,La Liga,2011/2012
50,11,22,Spain,La Liga,2010/2011
51,11,21,Spain,La Liga,2009/2010
52,11,41,Spain,La Liga,2008/2009
53,11,40,Spain,La Liga,2007/2008
54,11,39,Spain,La Liga,2006/2007
55,11,38,Spain,La Liga,2005/2006
56,11,37,Spain,La Liga,2004/2005
57,11,278,Spain,La Liga,1973/1974
58,182,281,Spain,Liga F,2023/2024
59,81,48,Argentina,Liga Profesional,1997/1998
60,81,275,Argentina,Liga Profesional,1981
61,7,235,France,Ligue 1,2022/2023
62,7,108,France,Ligue 1,2021/2022
63,7,27,France,Ligue 1,2015/2016
64,44,107,United States of America,Major League Soccer,2023
65,116,68,North and Central America,North American League,1977
66,49,107,United States of America,NWSL,2023
67,49,3,United States of America,NWSL,2018
68,2,27,England,Premier League,2015/2016
69,2,44,England,Premier League,2003/2004
70,12,27,Italy,Serie A,2015/2016
71,12,86,Italy,Serie A,1986/1987
72,131,281,Italy,Serie A Women,2023/2024
73,55,282,Europe,UEFA Euro,2024
74,55,43,Europe,UEFA Euro,2020
75,35,75,Europe,UEFA Europa League,1988/1989
76,53,315,Europe,UEFA Women's Euro,2025
77,53,106,Europe,UEFA Women's Euro,2022
78,72,107,International,Women's World Cup,2023
79,72,30,International,Women's World Cup,2019

In [4]:
# Filter to La Liga only
competitions[competitions['competition_name'] == 'La Liga'][
    ['competition_id', 'season_id', 'season_name']
]

    competition_id  season_id season_name
40              11         90   2020/2021
41              11         42   2019/2020
42              11          4   2018/2019
43              11          1   2017/2018
44              11          2   2016/2017
45              11         27   2015/2016
46              11         26   2014/2015
47              11         25   2013/2014
48              11         24   2012/2013
49              11         23   2011/2012
50              11         22   2010/2011
51              11         21   2009/2010
52              11         41   2008/2009
53              11         40   2007/2008
54              11         39   2006/2007
55              11         38   2005/2006
56              11         37   2004/2005
57              11        278   1973/1974

In [5]:
# La Liga 2015/2016 — get all matches
matches = sb.matches(competition_id=11, season_id=27)
print("Number of matches:", matches.shape[0])
matches[['match_id', 'home_team', 'away_team', 'home_score', 'away_score']].head(10)

C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Number of matches: 380

   match_id               home_team       away_team  home_score  away_score
0   3825739             Real Madrid  Sporting Gijón           5           1
1   3825848              Levante UD           Eibar           2           2
2   3825895              Las Palmas         Sevilla           2           0
3   3825894  RC Deportivo La Coruña          Getafe           0           2
4   3825855                  Málaga      Levante UD           3           1
5   3825908                Espanyol           Eibar           4           2
6   3825883                  Málaga      Las Palmas           4           1
7   3825900          Sporting Gijón      Villarreal           2           0
8   3825902          Rayo Vallecano      Levante UD           3           1
9   3825876              Real Betis          Getafe           2           1

In [6]:
import pandas as pd

all_shots = []                       # empty pile to collect shots
match_ids = matches['match_id'].tolist()

for i, mid in enumerate(match_ids):
    try:
        events = sb.events(match_id=mid)          # get everything in the match
        shots = events[events['type'] == 'Shot']  # keep only shots
        all_shots.append(shots)
    except Exception as e:
        print(f"Skipped match {mid}: {e}")

    if (i + 1) % 50 == 0:                          # progress every 50 matches
        print(f"Processed {i + 1}/{len(match_ids)} matches...")

# Stack all the shots into one big table
shots_df = pd.concat(all_shots, ignore_index=True)
print("\nDone! Total shots collected:", shots_df.shape[0])

C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Processed 50/380 matches...

C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Processed 100/380 matches...

C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Processed 150/380 matches...

C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Processed 200/380 matches...

C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Processed 250/380 matches...

C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Processed 300/380 matches...

C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Processed 350/380 matches...

C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\User\anaconda3\envs\xg\Lib\site-packages\statsbombpy\api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Done! Total shots collected: 9168

In [7]:
# Look at the key columns for building xG
shots_df[['player', 'team', 'shot_statsbomb_xg', 'shot_body_part',
          'shot_technique', 'shot_type', 'shot_outcome', 'location']].head(10)

,player,team,shot_statsbomb_xg,shot_body_part,shot_technique,shot_type,shot_outcome,location
0,Jonathan Rodríguez Menéndez,Sporting Gijón,0.125582,Left Foot,Normal,Open Play,Blocked,"[102.3, 49.3]"
1,Gareth Frank Bale,Real Madrid,0.245234,Head,Normal,Open Play,Goal,"[116.8, 44.5]"
2,Cristiano Ronaldo dos Santos Aveiro,Real Madrid,0.060526,Left Foot,Half Volley,Open Play,Goal,"[103.6, 32.2]"
3,Luka Modrić,Real Madrid,0.024467,Right Foot,Normal,Open Play,Blocked,"[90.7, 43.1]"
4,Karim Benzema,Real Madrid,0.088242,Right Foot,Overhead Kick,Open Play,Goal,"[109.1, 38.4]"
5,Luka Modrić,Real Madrid,0.036142,Left Foot,Normal,Open Play,Off T,"[102.2, 36.7]"
6,Cristiano Ronaldo dos Santos Aveiro,Real Madrid,0.382269,Left Foot,Normal,Open Play,Goal,"[110.3, 43.2]"
7,Jonathan Rodríguez Menéndez,Sporting Gijón,0.029750,Left Foot,Volley,Open Play,Blocked,"[94.9, 43.9]"
8,Jonathan Rodríguez Menéndez,Sporting Gijón,0.008997,Left Foot,Normal,Open Play,Saved,"[112.8, 60.4]"
9,Karim Benzema,Real Madrid,0.117174,Right Foot,Normal,Open Play,Blocked,"[109.3, 32.9]"

In [8]:
# How do shots end up? (our target variable)
print(shots_df['shot_outcome'].value_counts())
print()

# Turn outcome into a simple 1 = goal, 0 = not goal
shots_df['goal'] = (shots_df['shot_outcome'] == 'Goal').astype(int)
print("Goal rate:", round(shots_df['goal'].mean() * 100, 1), "%")

shot_outcome
Off T               2981
Saved               2216
Blocked             2081
Goal                1014
Wayward              599
Post                 209
Saved Off Target      35
Saved to Post         33
Name: count, dtype: int64

Goal rate: 11.1 %

In [9]:
# Does StatsBomb's xG roughly match the real goal rate? (sanity check)
print("Actual goal rate:      ", round(shots_df['goal'].mean() * 100, 1), "%")
print("Average StatsBomb xG:  ", round(shots_df['shot_statsbomb_xg'].mean() * 100, 1), "%")

Actual goal rate:       11.1 %
Average StatsBomb xG:   10.7 %

In [10]:
import sqlite3

# Create/connect to a database file in your project folder
conn = sqlite3.connect('football_xg.db')

# Keep the columns we need
cols_to_save = ['id', 'match_id', 'player', 'team', 'shot_statsbomb_xg',
                'shot_body_part', 'shot_technique', 'shot_type',
                'shot_outcome', 'location', 'goal']

shots_to_save = shots_df[cols_to_save].copy()
# location is a list -> store as text so SQLite accepts it
shots_to_save['location'] = shots_to_save['location'].astype(str)

shots_to_save.to_sql('shots', conn, if_exists='replace', index=False)
print("Saved to database!")

# Prove it with an actual SQL query
query = "SELECT COUNT(*) AS total_shots, SUM(goal) AS total_goals FROM shots"
result = pd.read_sql(query, conn)
print(result)

Saved to database!
   total_shots  total_goals
0         9168         1014